version: "3.7"

networks:
  licenta-nginx-php-mysql:
    driver: bridge
    ipam:
      config:
        - subnet: 160.100.0.0/16

volumes:
  db_data:

services:
  #nginx service
  licenta-nginx-service:
    image: nginx:stable-alpine
    container_name: licenta-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - licenta-php-service
      - licenta-mysql-service
    networks:
      licenta-nginx-php-mysql:
        ipv4_address: 160.100.0.5

  licenta-php-service:
    image: licenta-php-image
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: licenta-php-container
    ports:
      - "9000:9000"
    environment:
        PHP_IDE_CONFIG: serverName=licenta.local
    volumes:
      - ./app:/var/www/project
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      licenta-nginx-php-mysql:
        ipv4_address: 160.100.0.6

  licenta-mysql-service:
    image: mysql:8.0
    container_name: licenta-mysql-container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always, on-failure, unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: parola123
      MYSQL_DATABASE: licenta
      MYSQL_USER: user
      MYSQL_PASSWORD: parola123
    networks:
      licenta-nginx-php-mysql:
        ipv4_address: 160.100.0.7

  licenta-redis-service:
    image: redis:6.2
    container_name: licenta-redis-container
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      licenta-nginx-php-mysql:
        ipv4_address: 160.100.0.12

  licenta-mailer-service:
    image: schickling/mailcatcher
    container_name: licenta-mailcatcher-container
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      licenta-nginx-php-mysql:
        ipv4_address: 160.100.0.11

  licenta-rabbitmq-service:
    image: rabbitmq:3.9-management
    container_name: licenta-rabbitmq-container
    depends_on:
      - licenta-php-service
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        licenta-nginx-php-mysql:
            ipv4_address: 160.100.0.10