version: "3.7"

networks:
  healthconnect:
    driver: bridge
    ipam:
      config:
        - subnet: 160.100.0.0/16

volumes:
  db_data:

services:
  healthconnect-nginx-service:
    image: nginx:stable-alpine
    container_name: healthconnect-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - healthconnect-php-service
      - healthconnect-mysql-service
    networks:
      healthconnect:
        ipv4_address: 160.100.0.5

  healthconnect-php-service:
    image: healthconnect-php-image
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: healthconnect-php-container
    ports:
      - "9000:9000"
    environment:
        PHP_IDE_CONFIG: serverName=healthconnect.local
    volumes:
      - ./app:/var/www/app
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      healthconnect:
        ipv4_address: 160.100.0.6

  healthconnect-mysql-service:
    image: mysql:8.0
    container_name: healthconnect-mysql-container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always, on-failure, unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: parola123
      MYSQL_DATABASE: healthconnect
    networks:
      healthconnect:
        ipv4_address: 160.100.0.7

  healthconnect-redis-service:
    image: redis:6.2
    container_name: healthconnect-redis-container
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      healthconnect:
        ipv4_address: 160.100.0.12

  healthconnect-mailer-service:
    image: schickling/mailcatcher
    container_name: healthconnect-mailcatcher-container
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      healthconnect:
        ipv4_address: 160.100.0.11

  healthconnect-rabbitmq-service:
    image: rabbitmq:3.9-management
    container_name: healthconnect-rabbitmq-container
    depends_on:
      - healthconnect-php-service
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        healthconnect:
            ipv4_address: 160.100.0.10

  healthconnect-supervisor-service:
    image: healthconnect-supervisor-image
    build:
      context: .
      dockerfile: ./supervisor/Dockerfile
    container_name: healthconnect-supervisor-container
    depends_on:
      - healthconnect-php-service
      - healthconnect-redis-service
      - healthconnect-mailer-service
      - healthconnect-rabbitmq-service
    links:
        - healthconnect-php-service
        - healthconnect-redis-service
        - healthconnect-mailer-service
        - healthconnect-rabbitmq-service
    volumes:
        - ./:/var/www/
        - ./supervisor/supervisord.conf/:/etc/supervisor/conf.d/supervisord.conf
        - ./supervisor/crontab:/etc/cron.d/crontab
        - ./log:/var/log/supervisor/log
    restart: unless-stopped
    networks:
        healthconnect:
            ipv4_address: 160.100.0.4