version: "3.7"

networks:
  licenta-nginx-php-mysql:

volumes:
  db_data:

services:

  #nginx service
  licenta-nginx-service:
    image: nginx:stable-alpine
    container_name: licenta-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - licenta-php-service
      - licenta-mysql-service
    networks:
      - licenta-nginx-php-mysql

  licenta-php-service:
    image: licenta-php-image
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: licenta-php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - licenta-nginx-php-mysql

  licenta-mysql-service:
    image: mysql:8.0
    container_name: licenta-mysql-container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always, on-failure, unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: parola123
      MYSQL_DATABASE: licenta
      MYSQL_USER: user
      MYSQL_PASSWORD: parola123
    networks:
      - licenta-nginx-php-mysql