framework:
    messenger:
        failure_transport: failed

        transports:
            rabbitmq:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'email_exchange'
                        type: fanout
            failed: 'doctrine://default?queue_name=failed'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: rabbitmq
            Symfony\Component\Notifier\Message\ChatMessage: rabbitmq
            Symfony\Component\Notifier\Message\SmsMessage: rabbitmq

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
