security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_MEDIC
        ROLE_MEDIC: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_email_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy: true
            pattern: ^/admin
            provider: user_email_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                default_target_path: admin_main_page
            logout:
                path: admin_logout
                target: admin_login
        web:
            lazy: true
            provider: user_email_provider
            form_login:
                login_path: web_login
                check_path: web_login
                enable_csrf: true
                default_target_path: web_main_page
            logout:
                path: web_logout
                target: web_main_page
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds

    access_control:
#         - { path: ^/admin/login, roles: PUBLIC_ACCESS }
#         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
